#!/bin/bash
nodezmq_version="2.1.0"
stackio_version="0.2.x"
project_dir="/home/dotcloud/current/project"
node_root="/opt/node"
node_version="v0.8.9"

# Installing the zeromq library if it hasn't been yet.
# No system package for zeromq in Lucid :(
echo "# Checking for ZeroMQ presence"
test -f ~/.zmq_installed || (
    echo "# Installing zeromq-2.2.0"
    mkdir -p /home/dotcloud/installs/zeromq
    mkdir builds && cd builds
    wget http://download.zeromq.org/zeromq-2.2.0.tar.gz
    tar -xvf zeromq-2.2.0.tar.gz
    cd zeromq-2.2.0
    ./configure --prefix=/home/dotcloud/installs/zeromq; make; make install
    cd ../..
    rm -rf builds
    touch ~/.zmq_installed
)

echo "# Exporting PKG_CONFIG_PATH"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/home/dotcloud/installs/zeromq/lib/pkgconfig"

echo "# Downloading node-zmq $nodezmq_version tarball"
mkdir -p /tmp/zmqnode && rm -rf /tmp/zmqnode/* && cd /tmp/zmqnode
curl -L https://github.com/shin-/zeromq.node/tarball/$nodezmq_version | tar -zxf -

echo "# Moving downloaded folder to node_modules"
mkdir $project_dir/node_modules # If no package.json / no other dependency
rm -rf $project_dir/node_modules/zmq
mv shin--* $project_dir/node_modules/zmq
cd $project_dir/node_modules/zmq

echo "# node-waf configure build"
PKG_CONFIG_PATH=/home/dotcloud/installs/zeromq/lib/pkgconfig node-waf configure build

# Finally, we can install stack.io
echo "# npm install stack.io"
cd $project_dir && npm install zerorpc@0.9.x stack.io@$stackio_version